import { Landing } from "@/components/Landing";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-50 min-h-screen p-8">
        <div className="flex items-center flex-col justify-center">
          <h1 className="text-3xl font-bold">Ancient Warriors</h1>
          <h2 className="text-gray-700 text-lg">NFT Collection</h2>
        </div>

        <section className=" mt-4 rounded-lg bg-white shadow-lg p-4">
          <Landing />
        </section>
      </main>
    </>
  );
}
